Repository softwareconstruction240/autograder, pull requests merged in 2024-10, with the labels that each got.

#436 Provide contextualized note about potential issue with temporary code
  src/main/java/edu/byu/cs/controller/UserController.java
Labels: bug

#433 416 canvas preserve comprehensive startup nature of GitHub assignment
  src/main/java/edu/byu/cs/autograder/Grader.java
  src/main/java/edu/byu/cs/autograder/git/GitHelper.java
  src/main/java/edu/byu/cs/autograder/git/GitHubAssignmentGrader.java
  src/main/java/edu/byu/cs/autograder/score/Scorer.java
  src/main/java/edu/byu/cs/util/PhaseUtils.java
Labels: enhancement, important

#437 Code improvements
  src/main/java/edu/byu/cs/autograder/GradingException.java
  src/main/java/edu/byu/cs/autograder/test/PreviousPhasePassoffTestGrader.java
  src/main/java/edu/byu/cs/canvas/CanvasException.java
  src/main/java/edu/byu/cs/controller/SubmissionController.java
  src/main/java/edu/byu/cs/controller/TrafficController.java
  src/main/java/edu/byu/cs/controller/WebSocketController.java
  src/main/java/edu/byu/cs/util/SubmissionUtils.java
Labels: documentation, enhancement

#439 Disable the stubs of integration tests
  src/test/java/edu/byu/cs/autograder/git/GitHelperTest.java
Labels: clean-up

#435 430 fullstack enhance late penalty applied presentation experience
  src/main/java/edu/byu/cs/autograder/Grader.java
  src/main/java/edu/byu/cs/autograder/score/LateDayCalculator.java
  src/main/java/edu/byu/cs/autograder/score/Scorer.java
  src/main/java/edu/byu/cs/dataAccess/memory/SubmissionMemoryDao.java
  src/main/java/edu/byu/cs/dataAccess/sql/SqlDb.java
  src/main/java/edu/byu/cs/dataAccess/sql/SubmissionSqlDao.java
  src/main/java/edu/byu/cs/model/Rubric.java
  src/main/java/edu/byu/cs/model/Submission.java
  src/main/java/edu/byu/cs/util/SubmissionUtils.java
  src/main/resources/frontend/src/assets/base.css
  src/main/resources/frontend/src/types/types.ts
  src/main/resources/frontend/src/utils/utils.ts
  src/main/resources/frontend/src/views/StudentView/ResultsPreview.vue
  src/main/resources/frontend/src/views/StudentView/RubricItemView.vue
  src/main/resources/frontend/src/views/StudentView/SubmissionInfo.vue
Labels: enhancement, clean-up

#447 Remove temporary GitHub repo url migratory code
  src/main/java/edu/byu/cs/controller/UserController.java
Labels: clean-up
