Repository softwareconstruction240/autograder, pull requests merged in 2024-05, with the labels that each got.

#233 160 hold off submitting scores for low commit submissions
  src/main/java/edu/byu/cs/analytics/CommitAnalytics.java
  src/main/java/edu/byu/cs/analytics/CommitThreshold.java
  src/main/java/edu/byu/cs/analytics/CommitsByDay.java
  src/main/java/edu/byu/cs/autograder/Grader.java
  src/main/java/edu/byu/cs/autograder/GradingContext.java
  src/main/java/edu/byu/cs/autograder/git/CommitVerificationResult.java
  src/main/java/edu/byu/cs/autograder/git/GitHelper.java
  src/main/java/edu/byu/cs/autograder/git/specs.md
  src/main/java/edu/byu/cs/autograder/score/LateDayCalculator.java
  src/main/java/edu/byu/cs/autograder/score/Scorer.java
  src/main/java/edu/byu/cs/autograder/score/ScorerHelper.java
  src/main/java/edu/byu/cs/canvas/CanvasIntegrationImpl.java
  src/main/java/edu/byu/cs/controller/SubmissionController.java
  src/main/java/edu/byu/cs/dataAccess/ItemNotFoundException.java
  src/main/java/edu/byu/cs/dataAccess/SubmissionDao.java
  src/main/java/edu/byu/cs/dataAccess/SubmissionHelper.java
  src/main/java/edu/byu/cs/dataAccess/memory/SubmissionMemoryDao.java
  src/main/java/edu/byu/cs/dataAccess/sql/SqlDb.java
  src/main/java/edu/byu/cs/dataAccess/sql/SubmissionSqlDao.java
  src/main/java/edu/byu/cs/model/Rubric.java
  src/main/java/edu/byu/cs/model/Submission.java
  src/main/java/edu/byu/cs/util/PhaseUtils.java
  src/main/resources/frontend/src/types/types.ts
  src/main/resources/frontend/src/utils/utils.ts
  src/main/resources/frontend/src/views/PhaseView/PastSubmissions.vue
  src/main/resources/frontend/src/views/PhaseView/ResultsSection.vue
  src/test/java/edu/byu/cs/autograder/score/ScorerTest.java
Labels: enhancement, important

#347 125 accept divserse repo urls
  src/main/java/edu/byu/cs/autograder/Grader.java
  src/main/java/edu/byu/cs/controller/SubmissionController.java
  src/main/java/edu/byu/cs/server/Server.java
  src/test/java/edu/byu/cs/autograder/GraderTest.java
Labels: enhancement

#345 Student UI Clean-Up
  src/main/java/edu/byu/cs/controller/SubmissionController.java
  src/main/java/edu/byu/cs/dataAccess/SubmissionDao.java
  src/main/java/edu/byu/cs/dataAccess/memory/SubmissionMemoryDao.java
  src/main/java/edu/byu/cs/dataAccess/sql/SubmissionSqlDao.java
  src/main/java/edu/byu/cs/server/Server.java
  src/main/resources/frontend/src/App.vue
  src/main/resources/frontend/src/assets/base.css
  src/main/resources/frontend/src/assets/fontawesome/css/all.css
  src/main/resources/frontend/src/assets/fontawesome/css/all.min.css
  src/main/resources/frontend/src/assets/fontawesome/css/brands.css
  src/main/resources/frontend/src/assets/fontawesome/css/brands.min.css
  src/main/resources/frontend/src/assets/fontawesome/css/fontawesome.css
  src/main/resources/frontend/src/assets/fontawesome/css/fontawesome.min.css
  src/main/resources/frontend/src/assets/fontawesome/css/regular.css
  src/main/resources/frontend/src/assets/fontawesome/css/regular.min.css
  src/main/resources/frontend/src/assets/fontawesome/css/solid.css
  src/main/resources/frontend/src/assets/fontawesome/css/solid.min.css
  src/main/resources/frontend/src/assets/fontawesome/css/svg-with-js.css
  src/main/resources/frontend/src/assets/fontawesome/css/svg-with-js.min.css
  src/main/resources/frontend/src/assets/fontawesome/webfonts/fa-brands-400.ttf
  src/main/resources/frontend/src/assets/fontawesome/webfonts/fa-brands-400.woff2
  src/main/resources/frontend/src/assets/fontawesome/webfonts/fa-regular-400.ttf
  src/main/resources/frontend/src/assets/fontawesome/webfonts/fa-regular-400.woff2
  src/main/resources/frontend/src/assets/fontawesome/webfonts/fa-solid-900.ttf
  src/main/resources/frontend/src/assets/fontawesome/webfonts/fa-solid-900.woff2
  src/main/resources/frontend/src/assets/fontawesome/webfonts/fa-v4compatibility.ttf
  src/main/resources/frontend/src/assets/fontawesome/webfonts/fa-v4compatibility.woff2
  src/main/resources/frontend/src/components/Dropdown.vue
  src/main/resources/frontend/src/components/InfoPanel.vue
  src/main/resources/frontend/src/components/MoreInfo.vue
  src/main/resources/frontend/src/components/PopUp.vue
  src/main/resources/frontend/src/services/logsService.ts
  src/main/resources/frontend/src/services/submissionService.ts
  src/main/resources/frontend/src/stores/submissions.ts
  src/main/resources/frontend/src/stores/uiConfig.ts
  src/main/resources/frontend/src/utils/tableUtils.ts
  src/main/resources/frontend/src/utils/utils.ts
  src/main/resources/frontend/src/views/AdminView/AdminView.vue
  src/main/resources/frontend/src/views/AdminView/HonorChecker.vue
  src/main/resources/frontend/src/views/AdminView/StudentInfo.vue
  src/main/resources/frontend/src/views/AdminView/SubmissionInfo.vue
  src/main/resources/frontend/src/views/AdminView/SubmissionsView.vue
  src/main/resources/frontend/src/views/HomeView.vue
  src/main/resources/frontend/src/views/PhaseView/PastSubmissions.vue
  src/main/resources/frontend/src/views/PhaseView/PhaseView.vue
  src/main/resources/frontend/src/views/PhaseView/ResultsPopup.vue
  src/main/resources/frontend/src/views/PhaseView/ResultsSection.vue
  src/main/resources/frontend/src/views/PhaseView/RubricTable.vue
  src/main/resources/frontend/src/views/PhaseView/RubricTableRow.vue
  src/main/resources/frontend/src/views/StudentView/LiveStatus.vue
  src/main/resources/frontend/src/views/StudentView/ResultsPreview.vue
  src/main/resources/frontend/src/views/StudentView/RubricItemResultsView.vue
  src/main/resources/frontend/src/views/StudentView/RubricItemView.vue
  src/main/resources/frontend/src/views/StudentView/SubmissionHistory.vue
  src/main/resources/frontend/src/views/StudentView/SubmissionInfo.vue
  src/main/resources/frontend/yarn.lock
Labels: enhancement

#351 Fix lower score bug
  src/main/java/edu/byu/cs/autograder/score/Scorer.java
  src/main/java/edu/byu/cs/canvas/model/CanvasRubricAssessment.java
Labels: bug, enhancement

#355 Correct line counting issue
  src/main/java/edu/byu/cs/analytics/CommitAnalytics.java
  src/main/java/edu/byu/cs/autograder/git/CommitVerificationResult.java
  src/main/java/edu/byu/cs/autograder/git/GitHelper.java
  src/test/java/edu/byu/cs/autograder/score/ScorerTest.java
Labels: bug

#357 Fix commit verification null exception
  src/main/java/edu/byu/cs/autograder/Grader.java
  src/main/java/edu/byu/cs/autograder/git/GitHelper.java
  src/main/java/edu/byu/cs/model/Submission.java
Labels: bug

#359 Lower commit threshold to 5 changes in discussion with Prof. Wilkerson
  src/main/java/edu/byu/cs/autograder/Grader.java
Labels: important

#368 Load parent commits explicitly
  src/main/java/edu/byu/cs/analytics/CommitAnalytics.java
Labels: bug

#369 Disable canvas and compilation
  compose.yml
  src/main/java/edu/byu/cs/autograder/Grader.java
  src/main/java/edu/byu/cs/autograder/score/LateDayCalculator.java
  src/main/java/edu/byu/cs/autograder/score/Scorer.java
  src/main/java/edu/byu/cs/properties/ApplicationProperties.java
  src/main/java/edu/byu/cs/server/Server.java
Labels: enhancement

#336 Test 160 proper history verification
  src/main/java/edu/byu/cs/analytics/CommitAnalytics.java
  src/main/java/edu/byu/cs/autograder/git/GitHelper.java
  src/main/java/edu/byu/cs/dataAccess/DaoService.java
  src/test/java/edu/byu/cs/autograder/git/GitHelperPerformanceTest.java
  src/test/java/edu/byu/cs/autograder/git/GitHelperTest.java
  src/test/java/edu/byu/cs/autograder/git/GitHelperUtils.java
  src/test/java/edu/byu/cs/autograder/git/RepoContext.java
  src/test/java/edu/byu/cs/autograder/git/VerificationCheckpoint.java
  src/test/java/edu/byu/cs/autograder/score/ScorerTest.java
Labels: enhancement

#372 Simplify implementation of FileUtils.writeStringToFile()
  src/main/java/edu/byu/cs/util/FileUtils.java
Labels: enhancement

#374 Suppress expected warning output in tests
  src/main/java/edu/byu/cs/autograder/score/LateDayCalculator.java
  src/test/java/edu/byu/cs/autograder/score/LateDayCalculatorTest.java
Labels: enhancement
