Repository softwareconstruction240/autograder, pull requests merged in 2024-03, with the labels that each got.

#206 124 stop grading if it lowers score - fix null exception
  src/main/java/edu/byu/cs/autograder/Grader.java
  src/main/java/edu/byu/cs/canvas/CanvasIntegration.java
  src/main/java/edu/byu/cs/controller/SubmissionController.java
  src/main/java/edu/byu/cs/dataAccess/SubmissionDao.java
  src/main/java/edu/byu/cs/dataAccess/memory/SubmissionMemoryDao.java
  src/main/java/edu/byu/cs/dataAccess/sql/SubmissionSqlDao.java
  src/main/resources/frontend/src/views/PhaseView/ResultsSection.vue
Labels: enhancement

#215 Adjust late penalty calculation
  src/main/java/edu/byu/cs/util/DateTimeUtils.java
  src/test/java/edu/byu/cs/util/DateTimeUtilsTest.java
Labels: bug

#219 172 holidays and weekends dont extend late calculation
  src/main/java/edu/byu/cs/autograder/Grader.java
  src/main/java/edu/byu/cs/util/DateTimeUtils.java
  src/test/java/edu/byu/cs/util/DateTimeUtilsTest.java
  src/test/java/edu/byu/cs/util/days-late-with-holidays-common.jpg
  src/test/java/edu/byu/cs/util/days-late-with-holidays-due-on-holiday.jpg
  src/test/java/edu/byu/cs/util/days-late-with-holidays-friday-holiday-and-consecutive-holidays.jpg
  src/test/java/edu/byu/cs/util/days-late-with-holidays-holidays-on-weekends.jpg
  src/test/java/edu/byu/cs/util/days-late-without-holidays-1.jpg
  src/test/java/edu/byu/cs/util/days-late-without-holidays-2.jpg
Labels: enhancement

#222 158 front end admin update
  src/main/resources/frontend/src/utils/tableUtils.ts
  src/main/resources/frontend/src/utils/utils.ts
  src/main/resources/frontend/src/views/AdminView/AdminView.vue
  src/main/resources/frontend/src/views/AdminView/Analytics.vue
  src/main/resources/frontend/src/views/AdminView/HonorChecker.vue
  src/main/resources/frontend/src/views/AdminView/QueueStatus.vue
  src/main/resources/frontend/src/views/AdminView/StudentInfo.vue
  src/main/resources/frontend/src/views/AdminView/Students.vue
  src/main/resources/frontend/src/views/AdminView/StudentsView.vue
  src/main/resources/frontend/src/views/AdminView/SubmissionInfo.vue
  src/main/resources/frontend/src/views/AdminView/Submissions.vue
  src/main/resources/frontend/src/views/AdminView/SubmissionsView.vue
Labels: enhancement

#238 Load only 25 Submissions initially
  src/main/java/edu/byu/cs/controller/SubmissionController.java
  src/main/java/edu/byu/cs/dataAccess/SubmissionDao.java
  src/main/java/edu/byu/cs/dataAccess/memory/SubmissionMemoryDao.java
  src/main/java/edu/byu/cs/dataAccess/sql/SubmissionSqlDao.java
  src/main/java/edu/byu/cs/server/Server.java
  src/main/resources/frontend/src/services/adminService.ts
  src/main/resources/frontend/src/views/AdminView/SubmissionsView.vue
Labels: enhancement

#234 Add ability to send a canvas comment without a grade
  src/main/java/edu/byu/cs/canvas/CanvasIntegration.java
Labels: enhancement

#256 Allow submissions from admin panel
  src/main/java/edu/byu/cs/autograder/Grader.java
  src/main/java/edu/byu/cs/autograder/GradingContext.java
  src/main/java/edu/byu/cs/autograder/score/Scorer.java
  src/main/java/edu/byu/cs/autograder/test/UnitTestGrader.java
  src/main/java/edu/byu/cs/controller/SubmissionController.java
  src/main/java/edu/byu/cs/controller/netmodel/GradeRequest.java
  src/main/java/edu/byu/cs/dataAccess/sql/SqlDb.java
  src/main/java/edu/byu/cs/dataAccess/sql/SubmissionSqlDao.java
  src/main/java/edu/byu/cs/model/Submission.java
  src/main/java/edu/byu/cs/server/Server.java
  src/main/resources/frontend/src/components/Dropdown.vue
  src/main/resources/frontend/src/components/PopUp.vue
  src/main/resources/frontend/src/services/submissionService.ts
  src/main/resources/frontend/src/types/types.ts
  src/main/resources/frontend/src/views/AdminView/SubmissionInfo.vue
  src/main/resources/frontend/src/views/AdminView/SubmissionsView.vue
Labels: enhancement, help wanted
