Repository softwareconstruction240/autograder, pull requests merged in 2024-11, with the labels that each got.

#457 Make a component for the contributors on the About Page
  src/main/resources/frontend/src/components/AboutPage.vue
  src/main/resources/frontend/src/components/AboutPagePerson.vue
Labels: clean-up

#458 Consolidate grader classes
  src/main/java/edu/byu/cs/autograder/Grader.java
  src/main/java/edu/byu/cs/autograder/test/GitHubAssignmentGrader.java
  src/main/java/edu/byu/cs/autograder/test/QualityGrader.java
Labels: clean-up

#455 Frontend: ServerCommunicator
  src/main/java/edu/byu/cs/controller/AdminController.java
  src/main/java/edu/byu/cs/server/Server.java
  src/main/resources/frontend/src/App.vue
  src/main/resources/frontend/src/components/BannerMessage.vue
  src/main/resources/frontend/src/components/RepoEditor.vue
  src/main/resources/frontend/src/components/searchableList/ItemType.ts
  src/main/resources/frontend/src/components/searchableList/SearchableList.vue
  src/main/resources/frontend/src/network/ServerCommunicator.ts
  src/main/resources/frontend/src/network/ServerError.ts
  src/main/resources/frontend/src/services/adminService.ts
  src/main/resources/frontend/src/services/authService.ts
  src/main/resources/frontend/src/services/configService.ts
  src/main/resources/frontend/src/services/submissionService.ts
  src/main/resources/frontend/src/services/userService.ts
  src/main/resources/frontend/src/views/StudentView/ResultsPreview.vue
Labels: clean-up

#468 Update phase 6 passoff requirements
  src/main/java/edu/byu/cs/util/PhaseUtils.java
Labels: important

#450 Extract service logic from controllers
  src/main/java/edu/byu/cs/autograder/GradingObserverImpl.java
  src/main/java/edu/byu/cs/controller/AdminController.java
  src/main/java/edu/byu/cs/controller/CasController.java
  src/main/java/edu/byu/cs/controller/ConfigController.java
  src/main/java/edu/byu/cs/controller/SubmissionController.java
  src/main/java/edu/byu/cs/controller/UserController.java
  src/main/java/edu/byu/cs/controller/exception/BadRequestException.java
  src/main/java/edu/byu/cs/controller/exception/InternalServerException.java
  src/main/java/edu/byu/cs/controller/exception/PriorRepoClaimBlockageException.java
  src/main/java/edu/byu/cs/model/User.java
  src/main/java/edu/byu/cs/server/Server.java
  src/main/java/edu/byu/cs/service/AdminService.java
  src/main/java/edu/byu/cs/service/CasService.java
  src/main/java/edu/byu/cs/service/ConfigService.java
  src/main/java/edu/byu/cs/service/SubmissionService.java
  src/main/java/edu/byu/cs/service/UserService.java
Labels: clean-up

#478 Add Scheduled Live Phases Shutoff
  src/main/java/edu/byu/cs/controller/ConfigController.java
  src/main/java/edu/byu/cs/dataAccess/ConfigurationDao.java
  src/main/java/edu/byu/cs/server/Server.java
  src/main/java/edu/byu/cs/service/ConfigService.java
  src/main/java/edu/byu/cs/service/SubmissionService.java
  src/main/java/edu/byu/cs/util/PhaseUtils.java
  src/main/java/edu/byu/cs/util/Serializer.java
  src/main/resources/frontend/src/components/ShutdownWarning.vue
  src/main/resources/frontend/src/components/config/BannerConfigEditor.vue
  src/main/resources/frontend/src/components/config/ConfigSection.vue
  src/main/resources/frontend/src/components/config/ScheduleShutdownEditor.vue
  src/main/resources/frontend/src/services/configService.ts
  src/main/resources/frontend/src/stores/appConfig.ts
  src/main/resources/frontend/src/utils/utils.ts
  src/main/resources/frontend/src/views/AdminView/ConfigView.vue
  src/main/resources/frontend/src/views/HomeView.vue
Labels: enhancement

#452 Update README.md and split into several related files
  README.md
  docs/getting-started/db-insert-statements/insert-config-database.md
  docs/getting-started/db-insert-statements/insert-rubric-database.md
  docs/getting-started/db-insert-statements/update-rubric-database.md
  docs/getting-started/getting-started.md
  docs/getting-started/windows.md
Labels: documentation, help wanted

#485 add Instant default for config
  src/main/java/edu/byu/cs/dataAccess/sql/ConfigurationSqlDao.java
Labels: bug, important

#482 Add configuration of penalty magic numbers
  src/main/java/edu/byu/cs/autograder/score/LateDayCalculator.java
  src/main/java/edu/byu/cs/autograder/score/Scorer.java
  src/main/java/edu/byu/cs/controller/ConfigController.java
  src/main/java/edu/byu/cs/dataAccess/ConfigurationDao.java
  src/main/java/edu/byu/cs/dataAccess/DaoService.java
  src/main/java/edu/byu/cs/dataAccess/sql/ConfigurationSqlDao.java
  src/main/java/edu/byu/cs/model/request/ConfigPenaltyUpdateRequest.java
  src/main/java/edu/byu/cs/server/Server.java
  src/main/java/edu/byu/cs/service/ConfigService.java
  src/main/java/edu/byu/cs/service/SubmissionService.java
  src/main/java/edu/byu/cs/util/PhaseUtils.java
  src/main/resources/frontend/src/components/config/BannerConfigEditor.vue
  src/main/resources/frontend/src/components/config/ConfigSection.vue
  src/main/resources/frontend/src/components/config/LivePhaseConfigEditor.vue
  src/main/resources/frontend/src/components/config/PenaltyConfigEditor.vue
  src/main/resources/frontend/src/services/configService.ts
  src/main/resources/frontend/src/stores/appConfig.ts
  src/main/resources/frontend/src/views/AdminView/ConfigView.vue
Labels: enhancement, clean-up

#472 Simplify server communicator
  src/main/resources/frontend/src/network/ServerCommunicator.ts
  src/main/resources/frontend/src/network/ServerError.ts
  src/main/resources/frontend/src/services/adminService.ts
  src/main/resources/frontend/src/services/authService.ts
  src/main/resources/frontend/src/services/configService.ts
  src/main/resources/frontend/src/services/submissionService.ts
  src/main/resources/frontend/src/services/userService.ts
  src/main/resources/frontend/src/stores/submissions.ts
Labels: clean-up
