Repository softwareconstruction240/autograder, pull requests merged in 2025-06, with the labels that each got.

#593 Update Required Packages to Test
  src/main/java/edu/byu/cs/autograder/compile/verifers/TestLocationVerifier.java
  src/main/java/edu/byu/cs/util/PhaseUtils.java
Labels: clean-up

#595 Javadocs - Utils Module
  src/main/java/edu/byu/cs/autograder/compile/verifers/TestLocationVerifier.java
  src/main/java/edu/byu/cs/util/DateTimeUtils.java
  src/main/java/edu/byu/cs/util/FileUtils.java
  src/main/java/edu/byu/cs/util/JwtUtils.java
  src/main/java/edu/byu/cs/util/NetworkUtils.java
  src/main/java/edu/byu/cs/util/PhaseUtils.java
  src/main/java/edu/byu/cs/util/ProcessUtils.java
  src/main/java/edu/byu/cs/util/RepoUrlValidator.java
  src/main/java/edu/byu/cs/util/ResourceUtils.java
  src/main/java/edu/byu/cs/util/Serializer.java
  src/main/java/edu/byu/cs/util/SubmissionUtils.java
Labels: documentation

#543 Create SubmissionDaoTests file
  .github/workflows/tests.yml
  .gitignore
  pom.xml
  src/main/java/edu/byu/cs/dataAccess/daoInterface/SubmissionDao.java
  src/main/java/edu/byu/cs/dataAccess/sql/SqlDb.java
  src/test/java/edu/byu/cs/dataAccess/DaoTestUtils.java
  src/test/java/edu/byu/cs/dataAccess/SubmissionDaoTest.java
  src/test/resources/testdb.example.env
Labels: help wanted
