Repository softwareconstruction240/autograder, pull requests merged in 2025-01, with the labels that each got.

#500 Admin Repo URL Submission HTTP Prefix
  src/main/resources/frontend/src/utils/utils.ts
  src/main/resources/frontend/src/views/AdminView/SubmissionsView.vue
Labels: bug

#503 Enforce no forks
  src/main/java/edu/byu/cs/util/NetworkUtils.java
  src/main/java/edu/byu/cs/util/RepoUrlValidator.java
  src/test/java/edu/byu/cs/util/RepoUrlValidatorTest.java
Labels: enhancement

#505 Switch to Parameterized Tests in RepoUrlValidatorTests class #504
  pom.xml
  src/test/java/edu/byu/cs/util/RepoUrlValidatorTest.java
Labels: clean-up

#440 422 backend commits with same timestamp should be downgraded in severity to warning
  src/main/java/edu/byu/cs/analytics/CommitAnalytics.java
  src/main/java/edu/byu/cs/analytics/CommitsByDay.java
  src/main/java/edu/byu/cs/autograder/git/CommitValidation/CV.java
  src/main/java/edu/byu/cs/autograder/git/CommitValidation/CommitVerificationContext.java
  src/main/java/edu/byu/cs/autograder/git/CommitValidation/CommitVerificationStrategy.java
  src/main/java/edu/byu/cs/autograder/git/CommitValidation/DefaultGitVerificationStrategy.java
  src/main/java/edu/byu/cs/autograder/git/CommitValidation/Result.java
  src/main/java/edu/byu/cs/autograder/git/CommitVerificationResult.java
  src/main/java/edu/byu/cs/autograder/git/GitHelper.java
  src/test/java/edu/byu/cs/autograder/git/GitHelperTest.java
  src/test/java/edu/byu/cs/autograder/git/GitHelperUtils.java
  src/test/java/edu/byu/cs/autograder/git/VerificationCheckpoint.java
  src/test/java/edu/byu/cs/autograder/score/ScorerTest.java
Labels: enhancement

#499 Document git commit verification
  docs/git-commit-verification.md
  src/main/java/edu/byu/cs/autograder/git/CommitValidation/CommitVerificationStrategy.java
  src/main/java/edu/byu/cs/autograder/git/CommitValidation/DefaultGitVerificationStrategy.java
  src/main/java/edu/byu/cs/autograder/git/GitHelper.java
Labels: documentation

#509 Update holidays for 2025
  src/main/java/edu/byu/cs/autograder/score/LateDayCalculator.java
Labels: bug, clean-up

#498 ConfigurationSqlDao getValue type switch
  src/main/java/edu/byu/cs/dataAccess/sql/ConfigurationSqlDao.java
Labels: clean-up

#514 442 commitverification reduce undue penalties on students submitting early
  src/main/java/edu/byu/cs/autograder/Grader.java
  src/main/java/edu/byu/cs/autograder/git/CommitValidation/CommitVerificationStrategy.java
  src/main/java/edu/byu/cs/autograder/git/CommitValidation/DefaultGitVerificationStrategy.java
  src/main/java/edu/byu/cs/autograder/git/GitHelper.java
  src/main/java/edu/byu/cs/autograder/score/LateDayCalculator.java
  src/main/java/edu/byu/cs/autograder/score/Scorer.java
  src/test/java/edu/byu/cs/autograder/git/GitHelperTest.java
  src/test/java/edu/byu/cs/autograder/git/GitHelperUtils.java
  src/test/java/edu/byu/cs/autograder/score/LateDayCalculatorTest.java
  src/test/java/edu/byu/cs/autograder/score/MockLateDayCalculator.java
  src/test/java/edu/byu/cs/autograder/score/ScorerTest.java
  src/test/java/edu/byu/cs/autograder/score/days-early.jpg
Labels: enhancement

#521 511 verify future holidays are configured
  src/main/java/edu/byu/cs/autograder/score/LateDayCalculator.java
  src/test/java/edu/byu/cs/autograder/score/LateDayCalculatorTest.java
  src/test/java/edu/byu/cs/autograder/score/MockLateDayCalculator.java
Labels: enhancement, clean-up

#526 fix endpoint testing bug that prevents server from starting correctly
  src/main/java/edu/byu/cs/server/Server.java
  src/test/java/edu/byu/cs/server/ServerTest.java
Labels: bug, important

#529 Fix bug where repo change requests failed
  src/main/resources/frontend/src/components/RepoEditor.vue
  src/main/resources/frontend/src/network/ServerCommunicator.ts
  src/main/resources/frontend/src/services/userService.ts
Labels: bug, important

#524 Refactor Configuration Communication
  src/main/java/edu/byu/cs/controller/ConfigController.java
  src/main/java/edu/byu/cs/model/PrivateConfig.java
  src/main/java/edu/byu/cs/model/PublicConfig.java
  src/main/java/edu/byu/cs/server/Server.java
  src/main/java/edu/byu/cs/server/endpointprovider/EndpointProvider.java
  src/main/java/edu/byu/cs/server/endpointprovider/EndpointProviderImpl.java
  src/main/java/edu/byu/cs/service/ConfigService.java
  src/main/resources/frontend/src/App.vue
  src/main/resources/frontend/src/components/BannerMessage.vue
  src/main/resources/frontend/src/components/ShutdownWarning.vue
  src/main/resources/frontend/src/components/config/BannerConfigEditor.vue
  src/main/resources/frontend/src/components/config/ConfigSection.vue
  src/main/resources/frontend/src/components/config/CourseConfigEditor.vue
  src/main/resources/frontend/src/components/config/CourseIdConfigEditor.vue
  src/main/resources/frontend/src/components/config/LivePhaseConfigEditor.vue
  src/main/resources/frontend/src/components/config/PenaltyConfigEditor.vue
  src/main/resources/frontend/src/components/config/ScheduleShutdownEditor.vue
  src/main/resources/frontend/src/network/ServerCommunicator.ts
  src/main/resources/frontend/src/services/configService.ts
  src/main/resources/frontend/src/stores/appConfig.ts
  src/main/resources/frontend/src/stores/config.ts
  src/main/resources/frontend/src/stores/submissions.ts
  src/main/resources/frontend/src/views/AdminView/ConfigView.vue
  src/main/resources/frontend/src/views/HomeView.vue
  src/main/resources/frontend/src/views/LoginView.vue
  src/test/java/edu/byu/cs/server/ServerTest.java
  src/test/java/edu/byu/cs/server/endpointprovider/MockEndpointProvider.java
Labels: clean-up
