Repository softwareconstruction240/autograder, pull requests merged in 2025-02, with the labels that each got.

#537 Fix flakey commit amend test...
  src/test/java/edu/byu/cs/autograder/git/GitHelperTest.java
Labels: bug, clean-up

#532 Reduce commits out of bounds to warnings only
  .gitignore
  src/main/java/edu/byu/cs/analytics/CommitAnalytics.java
  src/main/java/edu/byu/cs/autograder/git/CommitValidation/DefaultGitVerificationStrategy.java
  src/test/java/edu/byu/cs/autograder/git/GitHelperTest.java
  src/test/java/edu/byu/cs/autograder/git/GitHelperUtils.java
Labels: enhancement

#538 432 intelligently evaluate history without tail hash
  src/main/java/edu/byu/cs/autograder/git/CommitValidation/DefaultGitVerificationStrategy.java
  src/test/java/edu/byu/cs/autograder/git/GitHelperTest.java
Labels: enhancement, clean-up

#542 Provide commit results in submission
  src/main/java/edu/byu/cs/analytics/CommitAnalytics.java
  src/main/java/edu/byu/cs/analytics/CommitsByDay.java
  src/main/java/edu/byu/cs/autograder/Grader.java
  src/main/java/edu/byu/cs/autograder/git/CommitValidation/CommitVerificationContext.java
  src/main/java/edu/byu/cs/autograder/git/CommitVerificationReport.java
  src/main/java/edu/byu/cs/autograder/git/CommitVerificationResult.java
  src/main/java/edu/byu/cs/autograder/git/GitHelper.java
  src/main/java/edu/byu/cs/autograder/score/Scorer.java
  src/main/java/edu/byu/cs/dataAccess/memory/SubmissionMemoryDao.java
  src/main/java/edu/byu/cs/dataAccess/sql/SqlDb.java
  src/main/java/edu/byu/cs/dataAccess/sql/SubmissionSqlDao.java
  src/main/java/edu/byu/cs/dataAccess/sql/helpers/SqlReader.java
  src/main/java/edu/byu/cs/model/Submission.java
  src/main/java/edu/byu/cs/util/Serializer.java
  src/test/java/edu/byu/cs/autograder/git/GitHelperUtils.java
  src/test/java/edu/byu/cs/autograder/score/ScorerTest.java
Labels: enhancement

#550 Improve test analyzer
  src/main/java/edu/byu/cs/autograder/test/TestAnalyzer.java
  src/main/java/edu/byu/cs/model/PrivateConfig.java
  src/main/java/edu/byu/cs/model/PublicConfig.java
  src/main/java/edu/byu/cs/model/QueueItem.java
  src/main/java/edu/byu/cs/model/RubricConfig.java
  src/main/java/edu/byu/cs/model/SetCourseIdsRequest.java
  src/main/java/edu/byu/cs/model/TestAnalysis.java
  src/main/java/edu/byu/cs/model/TestNode.java
Labels: bug

#530 Add dynamic configuration of Holidays
  src/main/java/edu/byu/cs/autograder/score/LateDayCalculator.java
  src/main/java/edu/byu/cs/controller/ConfigController.java
  src/main/java/edu/byu/cs/dataAccess/daoInterface/ConfigurationDao.java
  src/main/java/edu/byu/cs/model/PrivateConfig.java
  src/main/java/edu/byu/cs/model/request/ConfigHolidayUpdateRequest.java
  src/main/java/edu/byu/cs/server/Server.java
  src/main/java/edu/byu/cs/server/endpointprovider/EndpointProvider.java
  src/main/java/edu/byu/cs/server/endpointprovider/EndpointProviderImpl.java
  src/main/java/edu/byu/cs/service/ConfigService.java
  src/main/resources/frontend/src/components/config/HolidayConfigEditor.vue
  src/main/resources/frontend/src/network/ServerCommunicator.ts
  src/main/resources/frontend/src/services/configService.ts
  src/main/resources/frontend/src/stores/config.ts
  src/main/resources/frontend/src/utils/utils.ts
  src/main/resources/frontend/src/views/AdminView/ConfigView.vue
  src/test/java/edu/byu/cs/autograder/git/GitHelperUtils.java
  src/test/java/edu/byu/cs/autograder/score/LateDayCalculatorTest.java
  src/test/java/edu/byu/cs/autograder/score/MockLateDayCalculator.java
  src/test/java/edu/byu/cs/autograder/score/ScorerTest.java
  src/test/java/edu/byu/cs/server/ServerTest.java
  src/test/java/edu/byu/cs/server/endpointprovider/MockEndpointProvider.java
Labels: enhancement

#473 Migrate autograder to use Javalin
  pom.xml
  src/main/java/edu/byu/cs/controller/AdminController.java
  src/main/java/edu/byu/cs/controller/AuthController.java
  src/main/java/edu/byu/cs/controller/CasController.java
  src/main/java/edu/byu/cs/controller/ConfigController.java
  src/main/java/edu/byu/cs/controller/SubmissionController.java
  src/main/java/edu/byu/cs/controller/UserController.java
  src/main/java/edu/byu/cs/controller/WebSocketController.java
  src/main/java/edu/byu/cs/controller/exception/PriorRepoClaimBlockageException.java
  src/main/java/edu/byu/cs/controller/exception/ResourceForbiddenException.java
  src/main/java/edu/byu/cs/controller/exception/ResourceNotFoundException.java
  src/main/java/edu/byu/cs/controller/exception/UnauthorizedException.java
  src/main/java/edu/byu/cs/controller/exception/UnprocessableEntityException.java
  src/main/java/edu/byu/cs/controller/exception/WordOfWisdomViolationException.java
  src/main/java/edu/byu/cs/server/SerializerAdapter.java
  src/main/java/edu/byu/cs/server/Server.java
  src/main/java/edu/byu/cs/server/endpointprovider/EndpointProvider.java
  src/main/java/edu/byu/cs/server/endpointprovider/EndpointProviderImpl.java
  src/main/java/edu/byu/cs/service/AdminService.java
  src/main/java/edu/byu/cs/service/UserService.java
  src/main/java/edu/byu/cs/util/Serializer.java
  src/test/java/edu/byu/cs/server/ServerTest.java
  src/test/java/edu/byu/cs/server/endpointprovider/MockEndpointProvider.java
Labels: enhancement
